#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Diagnostic plot for the superseded 16-segment NSGA-II development run.

The final 15-segment multi-seed figure is generated by
nsga2/analyze_main_multiseed.py.
"""
import os, ast
import numpy as np, pandas as pd
import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt

from common_paths import DERIVED, GENERATED_FIGURES, GENERATED_TABLES, NSGA2

FIG, TAB, DAT = map(str, (GENERATED_FIGURES, GENERATED_TABLES, DERIVED))
OUT = str(NSGA2 / "legacy_main")
plt.style.use("ggplot"); SAVE = dict(dpi=600, bbox_inches="tight")

pf = pd.read_csv(os.path.join(OUT, "pareto_main.csv"))          # cost, evac, widths
hv = pd.read_csv(os.path.join(OUT, "hv_main.csv"))              # gen, hypervolume, ...
pf = pf.sort_values("cost")
c, e = pf["cost"].to_numpy(float), pf["evac"].to_numpy(float)
# knee = min normalized distance to ideal
nc = (c - c.min()) / max(c.max() - c.min(), 1e-9)
ne = (e - e.min()) / max(e.max() - e.min(), 1e-9)
knee = int(np.argmin(np.hypot(nc, ne)))

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
# (a) Pareto front, with old post-hoc front overlaid
old_p = os.path.join(DAT, "pareto_front.csv")
if os.path.exists(old_p):
    o = pd.read_csv(old_p).sort_values("Cost_Score")
    axes[0].plot(o["Cost_Score"], o["Evac_Score"], "x--", color="gray", ms=5, lw=1,
                 alpha=0.7, label="15D post-hoc set (weighted GA)")
axes[0].plot(c, e, "-o", color="crimson", ms=4, lw=1.8,
             label="Legacy 16D NSGA-II approximation")
axes[0].scatter([c[knee]], [e[knee]], marker="*", s=320, color="gold", edgecolors="k",
                zorder=6, label="Ideal-point compromise")
axes[0].set_xlabel("Building-demolition / land-take cost proxy"); axes[0].set_ylabel("Evacuation score")
axes[0].set_title("Superseded 16D development result (diagnostic only)")
axes[0].legend(fontsize=8); axes[0].grid(True, alpha=0.3)
# (b) hypervolume convergence
axes[1].plot(hv["gen"], hv["hypervolume"] / hv["hypervolume"].iloc[-1], "-o", ms=3, lw=2, color="tab:blue")
axes[1].set_xlabel("Offspring batch"); axes[1].set_ylabel("Legacy normalized HV diagnostic")
axes[1].set_title("Legacy HV log; final analysis uses front-only fixed-reference HV")
axes[1].grid(True, alpha=0.3)
fig.suptitle("Legacy NSGA-II development run (not used for final C2 conclusions)", y=1.02)
fig.tight_layout(); fig.savefig(os.path.join(FIG, "FigR_C2_nsga2.png"), **SAVE)

# representative solutions table
rows = [dict(Type="Min-cost", cost=round(c[0], 1), evac=round(e[0], 1), widths=pf["widths"].iloc[0]),
        dict(Type="Min-evac", cost=round(c[-1], 1), evac=round(e[-1], 1), widths=pf["widths"].iloc[-1]),
        dict(Type="Ideal-point compromise", cost=round(c[knee], 1), evac=round(e[knee], 1), widths=pf["widths"].iloc[knee])]
pd.DataFrame(rows).to_csv(os.path.join(TAB, "TableR_C2_nsga2_representative.csv"), index=False)
print(f"[nsga2 plot] front size={len(pf)} ideal-compromise=(cost {c[knee]:.0f}, evac {e[knee]:.0f}) "
      f"HV final={hv['hypervolume'].iloc[-1]:.0f}")
